### ISSUE TITLE
httr::verbose() not found with just pangaear loaded

### ISSUE THREAD

**Issue by gavinsimpson** [ropensci/pangaear#52]
One of the examples in `?pg_search` is

    pg_search(query='citation:Archer', config=verbose())

This fails with error

    Error in as.request(config) : could not find function "verbose"

Not sure what the intention was here; if you expect `httr::verbose()' to be available then you should re-export it from pangaear's namespace. Or the example could become

    pg_search(query='citation:Archer', config=httr::verbose())

(Also, it would be handy to run all examples as tests when not on CRAN so that issues like this are caught quickly)

**Comment by sckott** [comment]
the intention is to show how to pass in curl options. i'll just load httr for the examle, and will add `--run-dontrun` to travis file
