### ISSUE TITLE
Add GitHub topics

### ISSUE THREAD

**Issue by katrinleinweber** [ropensci/pangaear#64]
`research-data` & `webservice-client` for example ;-)

**Comment by sckott** [comment]
`research-data` sounds good, 

but https://github.com/topics/api-client seems like its more widely used than https://github.com/topics/webservice-client ?

**Comment by katrinleinweber** [comment]
I don't know whether PANGAEA calls what they provide an "API" or a "webservice". I'd just argue that providing download-only is more like the latter. Maybe using both topics is best for potential users in any case.

**Comment by sckott** [comment]
Did both
